version: "3.8"

services:
  nextjs:
    container_name: nextjs-app-example-loginPage-demo
    build:
      context: ./../
      dockerfile: Dockerfile
    ports:
      - "3097:3000"
    restart: always
    volumes:
      - ./../:/app
      - ./../app/node_modules
